# Generated by Django 4.1 on 2024-03-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0002_course_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
