# Generated by Django 4.1 on 2024-03-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
